### ISSUE TITLE
Both Fuses in Leon A do not spawn

### ISSUE THREAD

**Issue by RagguBaggu** [FuzzyGamesOn/RE2R_AP_Client#21]
I had received the Breakroom Hallway shutter fuse before getting into the game, and decided to use it at the start since the datapackage listed both fuses as items in the pool. Lo and Behold, the Main Hall fuse isnt in the pool, and I was softlocked without another Break Room fuse being cheated in.

**Comment by FuzzyGamesOn** [comment]
Yeah, we took Main Hall fuse out of the pool for A scenarios because people kept forgetting to get all the checks in East Hallway (especially the closet that only opens after you talk to Elliot) and softlocking themselves, so we automatically open the Main Hall shutter after talking to Marvin. Since the Main Hall fuse no longer has a use in A scenarios, we removed it from the pool.

The randomizer does attempt to prevent any fuses or the Bolt Cutters from showing up in the initial East Hallway and Main Hall checks, but there's a bug with that code that allowed it here. Was recently fixed in source, so we'll plan to get a release out for that in the coming weeks. :smiley: 

Oh, and the datapackage list of items isn't scenario-specific (but is character-specific), which is why it shows both fuses. But A scenario only has Break Room, B scenario only has Main Hall.

---

Also, for anyone else who gets unlucky and has this happen to them too, you can load the autosave that happens at Elliot and you should have / re-receive everything you got up to that point, including the fuse.

**Comment by FuzzyGamesOn** [comment]
This was fixed in the most recent release. Closing.
